### ISSUE TITLE
Formatting issues

### ISSUE THREAD

**Issue by unlimitedcoder2** [TatoExp/GRhinoV1#2]
In the file https://github.com/TatoExp/GRhinoV1/pull/1/commits/59c0a3bef322a8c524a6059ec8585a372b7a6b0f#diff-2d3b1d8591c2f75d210807692731fc84
InitializeComponent is formatted incorrectly

**Comment by TatoExp** [comment]
no

**Comment by unlimitedcoder2** [comment]
@TatoExp 👎

**Comment by unlimitedcoder2** [comment]
@TatoExp 👎

**Comment by unlimitedcoder2** [comment]
@TatoExp 👎

**Comment by unlimitedcoder2** [comment]
@TatoExp 👎

**Comment by unlimitedcoder2** [comment]
@TatoExp 👎
